config/routes.rb
NewspaperSubscription::Application.routes.draw do
  resources :users
  resources :subscription_plans
  resources :newspapers do
  	member do
  		match '/plan', :to => "subscription_plans#new"
  	end
  end
  resource :session

  match '/login', :to => "sessions#new"
  match '/logout', :to => "sessions#destroy", :via => :delete
  match '/register', :to => "users#new"
end

app/models/newspaper.rb
class Newspaper < ActiveRecord::Base
  attr_accessible :editor, :title, :subscription_plans_attributes

  has_many :subscription_plans, :inverse_of => :newspaper
  has_many :subscribers, :through => :subscription_plans
  validates :title, :presence => true

  accepts_nested_attributes_for :subscription_plans,
  															:reject_if => lambda { |plan| plan[:weekly].blank? || plan[:price].blank?}
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
	attr_accessible :subscription_plan_id, :subscriber_id

  belongs_to :subscription_plan
  belongs_to :subscriber, :class_name => 'User', :foreign_key => :subscriber_id, :inverse_of => :subscriptions

  validates :subscription_plan_id, :subscriber, :presence => true
  # attr_accessible :title, :body
end

app/models/subscription_plan.rb
class SubscriptionPlan < ActiveRecord::Base
  attr_accessible :price, :weekly, :newspaper_id

  belongs_to :newspaper, :inverse_of => :subscription_plans

  has_many :subscriptions

  validates :price, :newspaper, :presence => true
  validates :weekly, :inclusion => [true, false]

  def render_plan_name
  	"#{weekly ? "Weekly" : "Daily"} -- #{price}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password_digest, :password, :password_confirmation, :subscriptions, :subscriptions_attributes
  has_many :subscription_plans, :through => :subscriptions
  has_many :subscriptions, :inverse_of => :subscriber

  accepts_nested_attributes_for :subscriptions
  has_secure_password

  validates :email, :name, :password_digest, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/newspapers_controller.rb
class NewspapersController < ApplicationController
	def new
		@newspaper = Newspaper.new
		3.times { @newspaper.subscription_plans.build }
	end
	def create
		@newspaper = Newspaper.new(params[:newspaper])
		@newspaper.save!
		if @newspaper.save
			redirect_to newspaper_path(@newspaper)
		else
			render :new
		end
	end
	def edit
		@newspaper = Newspaper.find(params[:id])
	end
	def update
		@newspaper = Newspaper.find(params[:id])
		if @newspaper.update_attributes(params[:newspaper])
			redirect_to newspaper_path(@newspaper)
		else
			render :edit
		end
	end
	def index
		@newspapers = Newspaper

		@newspapers = @newspapers.all
	end
	def show
		@newspaper = Newspaper.find(params[:id])
	end

	def destroy
		@newspaper = Newspaper.find(params[:id])
		@newspaper.destroy
		redirect_to newspapers_path
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		@email = ""
	end

	def create
		@email = params[:email]
		user = User.find_by_email(@email)
		if user && user.authenticate(params[:password])
			user.remember_token = SecureRandom.hex(16)
			session[:remember_token] = user.remember_token
			user.save!
			redirect_to user_path(user)
		else
			flash.now[:login_error] = "The credentials entered are invalid."
			render :back
		end
	end

	def destroy
		logout
		redirect_to login_path
	end
end

app/controllers/subscription_plans_controller.rb
class SubscriptionPlansController < ApplicationController
	def new
		@subscription_plan = SubscriptionPlan.new
		@id = params[:id]
	end
	def create
		@subscription_plan = SubscriptionPlan.new(params[:subscription_plan])
		@id = params[:subscription_plan][:newspaper_id]
		if @subscription_plan.save
			if params[:id].nil?
				redirect_to newspapers_path
			else
				redirect_to newspaper_path(params[:id])
			end
		else
			render :new
		end
	end
	def edit
	end
	def update
	end

	def destroy
		@subscription_plan = SubscriptionPlan.find(params[:id])
		@subscription_plan.destroy
		redirect_to newspaper_path(@subscription_plan.newspaper_id)
	end

	def show
		@subscription_plan = SubscriptionPlan.includes(:newspaper).find(params[:id])
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end
	def create

		@user = User.new(params[:user])
		if @user.save!
			redirect_to login_path
		else
			flash.now[:creation]
			render :new
		end
	end
	def edit
		@user = User.find(params[:id])
	end
	def update
		@user = User.find(params[:id])
		if @user.update_attributes(params[:user])
			redirect_to user_path(@user)
		else
			render :edit
		end
	end
	def index
		@users = User.all
	end
	def show
		@user = User.find(params[:id])
	end
	def destroy
		@user = User.find(params[:id])
		@user.destroy
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/newspapers_helper.rb
module NewspapersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def current_user
		return nil if session[:remember_token].nil?
		@user ||= User.find_by_remember_token(session[:remember_token])
	end
	def logout
		unless current_user.nil?
			current_user.remember_token = nil
			current_user.save!
		end
		
		reset_session		
	end
end

app/helpers/subscription_plans_helper.rb
module SubscriptionPlansHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navigation.html.erb
<% if session[:remember_token].nil? %>
	<%= link_to "Login", login_path %>
	<%= link_to "Register", register_path %>
<%else%>
	<%= link_to "Logout", logout_path, :method => :delete %>
<%end%>

<%= link_to "Newspapers", newspapers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewspaperSubscription</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>


<%= render :partial => "/layouts/navigation" %>
</body>
</html>

app/views/newspapers/index.html.erb
<h1>Newspapers</h1>
<ul>
	<% @newspapers.each do |newspaper| %>
		<li>
			<%= link_to newspaper.title, newspaper_path(newspaper) %>
			--
			<small>
				<%= newspaper.editor %>
			</small>
		</li>
	<% end %>
</ul>
<%= link_to "Add", new_newspaper_path %>

app/views/newspapers/new.html.erb
<h1>Create Newspaper</h1>
<%= form_for(@newspaper) do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>
	<br>
	<%= f.label :editor %>
	<%= f.text_field :editor %>
	<br>
	<%= f.fields_for :subscription_plans do |plan_form| %>
		<%= plan_form.label :price %>
		<%= plan_form.text_field :price %>
		<br>
		<%= plan_form.label :weekly, "Daily", :value => false %>
		<%= plan_form.radio_button :weekly, false, :checked => true %>
		<br>
		<%= plan_form.label :weekly, "Weekly", :value => true %>
		<%= plan_form.radio_button :weekly, true %>
		<br>
	<% end %>
	<%= f.submit "Submit Newspaper" %>
<% end %>

app/views/newspapers/show.html.erb
<h1>
	<%= @newspaper.title%>
</h1>
<p>
	Editor: <%= @newspaper.editor %>
	<br>
	<br>
	<% if @newspaper.subscription_plans.empty? %>
		No Available Subscription Plans
	<% else %>
		Available Subscription Plans:
		<br>
		<ol>
			<% @newspaper.subscription_plans.each do |subscription_plan| %>
				<li>
					<%= render :partial => "/subscription_plans/display",
						:locals => {:title => @newspaper.title,
											  :subscription_plan => subscription_plan}
					%>
				</li>
			<% end %>
		</ol>
	<%end %>
	<br>
	<br>
	<%= link_to "Add Plan Type", plan_newspaper_path(@newspaper) %>
</p>

<%= link_to "Delete", newspaper_path(@newspaper), :method => :delete %>

app/views/subscription_plans/_display.html.erb
<small>
Format: <%= subscription_plan.weekly ? "Weekly" : "Daily" %>
<br>
Price: <%= subscription_plan.price %>
<br>
<%= link_to "View", subscription_plan_path(subscription_plan)%>
 | 
<%= link_to "Register", "#"%>
<br>
</small>

app/views/subscription_plans/new.html.erb
<h1>
	Add Subscription Plan
</h1>
<%= form_for(@subscription_plan) do |f| %>
	<% if @id %>
		<%= f.hidden_field :newspaper_id, :value => @id %>
	<% else %>
		<%= f.label :newspaper_id, "Newspaper" %>
		<%= f.collection_select :newspaper_id, Newspaper.all, :id, :title%>
		<br>
	<% end %>
	<%= f.label :price %>
	<%= f.text_field :price %>
	<br>
	<%= f.label :weekly, "Daily", :value => false %>
	<%= f.radio_button :weekly, false, :checked => true %>
	<br>
	<%= f.label :weekly, "Weekly", :value => true %>
	<%= f.radio_button :weekly, true %>
	<br>
	<%= f.submit "Add Plan" %>
<% end %>

app/views/subscription_plans/show.html.erb
<h1>
	Subscription Plan for: <%=@subscription_plan.newspaper.title%>
</h1>
<p>
	<b>Details:</b>
	<br>
	Format: <%= @subscription_plan.weekly ? "Weekly" : "Daily" %>
	<br>
	Price: <%= @subscription_plan.price %>
	<br>

	<%= link_to "View Newspaper Page",
		newspaper_path(@subscription_plan.newspaper_id)
	%>
	<br>
	<%= link_to "Delete Plan Type",
		subscription_plan_path(@subscription_plan),
		:method => :delete
	%>
</p>

app/views/users/new.html.erb
<h1>Register</h1>
<%= form_for(@user) do |f| %>

	<%= f.label :email %>
	<%= f.text_field :email %>
	<br>

	<%= f.label :name %>
	<%= f.text_field :name %>
	<br>

	<%= f.label :password %>
	<%= f.password_field :password %>
	<br>

	<%= f.label :password_confirmation %>
	<%= f.password_field :password_confirmation %>
	<br>

	Available Subscriptions:
	<br>
	<% SubscriptionPlan.includes(:newspaper).all.each do |plan|%>
		<input type="checkbox" name="user[subscriptions_attributes][][subscription_plan_id]" id="<%=plan.render_plan_name%>", value="<%=plan.id%>">
		<label for="<%=plan.render_plan_name%>">
			<%= plan.newspaper.title%>, <%=plan.render_plan_name%>
		</label>
		<br>
	<% end %>
	<br>
	<%plans =  SubscriptionPlan.includes(:newspaper).all %>
	<% Newspaper.all.each do |newspaper| %>
		<%relevant_plans = plans.select {|plan| plan.newspaper_id == newspaper.id }%>
		<% next if relevant_plans.empty?%>
		<select name="user[subscriptions_attributes][][subscription_plan_id]"
						id="<%=newspaper.id%>">
			<%=options_from_collection_for_select(
				relevant_plans,
				:id,
				:render_plan_name
				)
			%>
		</select>
		<label for="<%=newspaper.id%>"><%=newspaper.title%></label>
		<br>
	<%end%>

	
	<%= f.submit "Register" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>